//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriptionsProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SubscribeMembers_DBEntities : DbContext
    {
        public SubscribeMembers_DBEntities()
            : base("name=SubscribeMembers_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminPermission> AdminPermissions { get; set; }
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<SubscriptionTransaction> SubscriptionTransactions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRegisterDepozit> UserRegisterDepozits { get; set; }
    }
}
